// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrsusmneomdytajifstc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyc3VzbW5lb21keXRhamlmc3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0OTgwNjUsImV4cCI6MjA1NjA3NDA2NX0.IL7nV7h6bI_imV-39o9iqEZKCW7ndY9WDMrgLDpZA7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);